spring:
  datasource:
    url: jdbc:postgresql://localhost/tourapp
    username: postgres
    password: salam123
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8081/auth/realms/traveller/protocol/openid-connect/certs'
          issuer-uri: 'http://localhost:8081/auth/realms/traveller'

keycloak:
  auth-server-url: http://localhost:8081/auth/
  ssl-required: external
  realm: traveller
  resource: tour-app
  credentials:
    secret: b81adc70-34f9-4d83-8b3f-ce6521ce5599
  bearer-only: true
  principal-attribute: preferred_username


keycloak-server:
  product-realm:
    name: traveller
    roles:
      initial: 'not-verified'
      standard: 'app-user'
  admin-realm:
    server-url: http://localhost:8081/auth/
    username: jon_snow883
    password: salam123
    client-id: admin-cli
    name: master